<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.11">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.7.11">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.meta.FilteredClassifier" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.unsupervised.attribute.RemoveByName -E .*EDEM.*|.*EDFU.*|.*EDT07.*|.*S140-.*&quot;</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.LibLINEAR</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-S</object>
            <object class="java.lang.String" name="6">7</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-E</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-B</object>
            <object class="java.lang.String" name="12">1.0</object>
            <object class="java.lang.String" name="13">-P</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.unsupervised.attribute.RemoveByName -E .*EDFU.*|.*EDT07.*|.*S140-.*&quot;</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.LibLINEAR</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-S</object>
            <object class="java.lang.String" name="6">7</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-E</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-B</object>
            <object class="java.lang.String" name="12">1.0</object>
            <object class="java.lang.String" name="13">-P</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.unsupervised.attribute.RemoveByName -E .*EDEM.*|.*EDT07.*|.*S140-.*&quot;</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.LibLINEAR</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-S</object>
            <object class="java.lang.String" name="6">7</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-E</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-B</object>
            <object class="java.lang.String" name="12">1.0</object>
            <object class="java.lang.String" name="13">-P</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.unsupervised.attribute.RemoveByName -E .*EDEM.*|.*EDFU.*|.*S140-.*&quot;</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.LibLINEAR</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-S</object>
            <object class="java.lang.String" name="6">7</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-E</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-B</object>
            <object class="java.lang.String" name="12">1.0</object>
            <object class="java.lang.String" name="13">-P</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.unsupervised.attribute.RemoveByName -E .*EDEM.*|.*EDFU.*|.*EDT07.*&quot;</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.LibLINEAR</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-S</object>
            <object class="java.lang.String" name="6">7</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-E</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-B</object>
            <object class="java.lang.String" name="12">1.0</object>
            <object class="java.lang.String" name="13">-P</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LibLINEAR" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-S</object>
            <object class="java.lang.String" name="1">7</object>
            <object class="java.lang.String" name="2">-C</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-E</object>
            <object class="java.lang.String" name="5">0.01</object>
            <object class="java.lang.String" name="6">-B</object>
            <object class="java.lang.String" name="7">1.0</object>
            <object class="java.lang.String" name="8">-P</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">/Users/admin/workspace/TwitterSentLex/testTweets/6HumanPosNegLex.arff</object>
      <object class="java.io.File" name="1">/Users/admin/workspace/TwitterSentLex/testTweets/SandersPosNegLex.arff</object>
      <object class="java.io.File" name="2">/Users/admin/workspace/TwitterSentLex/testTweets/SemEvalPosNegLex.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">10</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">weka_experiment4852642550494062816.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">/var/folders/jb/y0551jfj74sfhcjly12tp6sh0000gp/T/weka_experiment4852642550494062816.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
